In [11]:
# Introduction to Numpy -----> 
# Numpy is an open source library that is used for scientific calculations . 

### Why Numpy is better than List ? 
# (1). List hetrogenous data type and Numpy homogenous data type .
# (2). List take more memory as compare to Numpy . 
# (3). List take more time execution as compare to Numpy . 

In [29]:
 #!pip install numpy

In [13]:
import numpy as np 

In [14]:
a = [1,45,90]
type(a) 

list

In [30]:
b = np.array(a) 
b

array([0., 0., 0.])

In [16]:
type(b) 

numpy.ndarray

# How can we create a user-defiend Array ? 

In [17]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter number:"))
    a.append(val) 
# print(a) 
b = np.array(a)
b

Enter size: 3
Enter number: 1
Enter number: 2
Enter number: 3


array([1, 2, 3])

In [18]:
type(b) 

numpy.ndarray

# How can we check shape , size and dimension of an array ? 

In [19]:
a = [[1,2,3,0], [4,5,6,7],[7,8,9,3]]
b = np.array(a) 
b

array([[1, 2, 3, 0],
       [4, 5, 6, 7],
       [7, 8, 9, 3]])

In [ ]:
print("Total Shape = " , b.shape)  ###shape = n(rows) , n(columns) 

In [21]:
print("Total Elements = " , b.size)  ### size = n(rows) * n(columns) 

Total Elements =  12


In [22]:
print("Total Dimension = " , b.ndim)  ### ndim stands for n_dimension ---> 2 (x,y)

Total Dimension =  2


In [23]:
# Pre-defined functions in Numpy 

In [24]:
# (1). zeros() ----> It will return an array in which all the values will be 0 in 
# either one-dimensional or multi-dimensional . 

In [25]:
a = np.zeros(3) 
a

array([0., 0., 0.])

In [26]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
print("Total Shape =", a.shape)
print("Total Elements =", a.size)

Total Shape = (3,)
Total Elements = 3


In [31]:
print("Total Shape =", b.shape)
print("Total Elements =", b.size)

Total Shape = (3,)
Total Elements = 3
