In [36]:
import numpy as np 

In [37]:
#Reshaping the array

In [38]:
# n(rows) * n(coulums) = n(total_elements)
#total_elements =12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3

In [39]:
a = np.arange(1,13,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
#a.reshape(6,3) , beacuse 6*3=18

In [44]:
#Oprations on array

In [45]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [46]:
a**2

array([ 1,  4,  9, 16])

In [47]:
a*3

array([ 3,  6,  9, 12])

In [48]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [49]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [50]:
a+b

array([[ 6,  8],
       [10, 12]])

In [51]:
a-b

array([[-4, -4],
       [-4, -4]])

In [52]:
a*b  ###not

array([[ 5, 12],
       [21, 32]])

In [53]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [54]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.sum(a) ###total sum

np.int64(45)

In [57]:
np.sum(a, axis =0) ### coulum wise sum

array([12, 15, 18])

In [59]:
np.sum(a, axis =1) ### row wise sum

array([ 6, 15, 24])

In [61]:
#unique() ----->  it will return unique elements of array and its indexing and total accurance

In [64]:
a = np.array([1,2,2,2,2,2,2,2,2,2,3,1,4,5])
np.unique(a, return_index=True , return_counts = True)

(array([1, 2, 3, 4, 5]), array([ 0,  1, 10, 12, 13]), array([2, 9, 1, 1, 1]))

In [65]:
#linespace() ---> it will create an array in eh==which gap of values will br=e equal

In [70]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [71]:
# Hstack and vstack

In [72]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])


In [73]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])