In [2]:
import numpy as np 

In [3]:
#(02). ones() > it will create an array in which all the values are 1.
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [4]:
#(3) eye() > it will create an array inm which digonal positonal
#elements will be 1 and rest all are 0.

In [5]:
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#(4). diag > using this method, we can create an array in which can
#cutomize our digonal positional elements

In [7]:
a = np.diag([1,45,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [8]:
#(5). Random module

In [9]:
#(a) Randit() --> it will genrate random numbers in a given range.
#syntex: np.random.randit(min_value, max_value , total_numbers)

In [12]:
a = np.random.randint(1,10,3)
a

array([9, 3, 2], dtype=int32)

In [13]:
#(b) . Rand() --> it will genrate random numbers in range 0-1

In [14]:
a = np.random.rand(3,3)
a

array([[0.91964044, 0.0922317 , 0.03248581],
       [0.57148435, 0.85867447, 0.64522824],
       [0.89759096, 0.85972641, 0.72153877]])

In [15]:
# (c). seed() ----> it will fix our random genrated data.

In [16]:
np.random.seed(30)
a = np.random.randint(1,10,3)
a

array([6, 6, 5], dtype=int32)

In [17]:
# (6). view vs copy ---->
#view means modification in original dataset.
# copy means modification in duplicate data.

In [18]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5]
b[:] =0
b

array([0, 0, 0])

In [19]:
a

array([1, 2, 0, 0, 0, 6, 7, 8, 9])

In [24]:
a=  np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5].copy()
b[:] =0
b


array([0, 0, 0])

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])